version: '3.7'

services:

  vue-dockerized-app:
    container_name: vue-dockerized-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5173:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
